## POSTTEST04
## Rausyanfikr Adi Karmayoga 
## 2009106020

In [245]:
import pandas as pd
import numpy as np

In [246]:
df = pd.read_csv('data-credit-card.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   600 non-null    object
 1   Gender               600 non-null    object
 2   Age                  600 non-null    int64 
 3   Region_Code          600 non-null    object
 4   Occupation           600 non-null    object
 5   Channel_Code         600 non-null    object
 6   Vintage              600 non-null    int64 
 7   Credit_Product       535 non-null    object
 8   Avg_Account_Balance  600 non-null    int64 
 9   Is_Active            600 non-null    object
 10  Is_Lead              600 non-null    int64 
dtypes: int64(4), object(7)
memory usage: 51.7+ KB


In [247]:
df.head()

ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0  NNVBBKZB  Female   73       RG268          Other           X3       43   
1  IDD62UNG  Female   30       RG277       Salaried           X1       32   
2  HD3DSEMC  Female   56       RG268  Self_Employed           X3       26   
3  BF3NC7KV    Male   34       RG270       Salaried           X1       19   
4  TEASRWXV  Female   30       RG282       Salaried           X1       33   

  Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  
0             No              1045696        No        0  
1             No               581988        No        0  
2             No              1484315       Yes        0  
3             No               470454        No        0  
4             No               886787        No        0

- Membagi dataset menjadi <b>training set</b> dan <b>testing set</b> dengan proporsi 70:30

In [248]:
X = df.iloc[:,:-1] # Target
y = df.iloc[:,-1] # Feature

In [249]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [250]:
print("Dimensi X_train : ", x_train.shape)
print("Dimensi X_train : ", x_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test  : ", y_test.shape)

Dimensi X_train :  (420, 10)
Dimensi X_train :  (180, 10)
Dimensi y_train :  (420,)
Dimensi y_test  :  (180,)


- Melakukan <b>normalisasi</b> data pada salah satu attribute menggunakan <b>Min Max scaler</b>

In [251]:
copy_dataset = df[[ 'Age', 'Vintage', 'Avg_Account_Balance', 'Is_Lead' ]]

print("Nilai Data Sebelum scaling : ")
print(copy_dataset)

Nilai Data Sebelum scaling : 
     Age  Vintage  Avg_Account_Balance  Is_Lead
0     73       43              1045696        0
1     30       32               581988        0
2     56       26              1484315        0
3     34       19               470454        0
4     30       33               886787        0
..   ...      ...                  ...      ...
595   28       20               348007        0
596   26       13              1664522        0
597   78       68              2308962        0
598   50      111              1696135        0
599   78       45              2983564        0

[600 rows x 4 columns]


In [252]:
from sklearn.preprocessing import MinMaxScaler

MinMaxScaler = MinMaxScaler()
Scaled_data = MinMaxScaler.fit_transform(copy_dataset)

print("Nilai Data setelah scaling : ")
print(Scaled_data)
print("\n Nilai standar deviasi: ", np.std(Scaled_data))

Nilai Data setelah scaling : 
[[0.80327869 0.29824561 0.11309168 0.        ]
 [0.09836066 0.20175439 0.05291824 0.        ]
 [0.52459016 0.14912281 0.17000943 0.        ]
 ...
 [0.8852459  0.51754386 0.27702042 0.        ]
 [0.42622951 0.89473684 0.19749643 0.        ]
 [0.8852459  0.31578947 0.3645607  0.        ]]

 Nilai standar deviasi:  0.2972966135296252


- Melakukan <b>standarisasi</b> pada dataset

In [253]:
copy_dataset = df[[ 'Age', 'Vintage', 'Avg_Account_Balance', 'Is_Lead' ]]

print("Nilai Data Sebelum scaling : ")
print(copy_dataset)

Nilai Data Sebelum scaling : 
     Age  Vintage  Avg_Account_Balance  Is_Lead
0     73       43              1045696        0
1     30       32               581988        0
2     56       26              1484315        0
3     34       19               470454        0
4     30       33               886787        0
..   ...      ...                  ...      ...
595   28       20               348007        0
596   26       13              1664522        0
597   78       68              2308962        0
598   50      111              1696135        0
599   78       45              2983564        0

[600 rows x 4 columns]


In [254]:
from sklearn.preprocessing import StandardScaler

StandardScaler = StandardScaler()
Scaled_data = StandardScaler.fit_transform(copy_dataset)

print("Nilai Data setelah scaling : ")
print(Scaled_data)
print("\n Nilai standar deviasi: ", np.std(Scaled_data))

Nilai Data setelah scaling : 
[[ 2.03885441 -0.07794082 -0.10661399 -0.55938384]
 [-0.90443363 -0.42551477 -0.63956738 -0.55938384]
 [ 0.87522891 -0.61510056  0.39750387 -0.55938384]
 ...
 [ 2.3810972   0.71199996  1.34529519 -0.55938384]
 [ 0.46453755  2.07069811  0.6409549  -0.55938384]
 [ 2.3810972  -0.01474556  2.12063533 -0.55938384]]

 Nilai standar deviasi:  1.0


- Melakukan <b>Data cleaning</b> pada data dengan <b>nilai null</b>. Mengganti nilai null sesuai ketentuan. (<b>bilangan bulat : median/modus, bilangan desimal : mean, tulisan : modus</b>).

In [255]:
print("Jumlah record yang memiliki nilai null: ")
print(df.isna().sum())

tipeData_creditProduct = df.dtypes['Credit_Product']
print("\nTipe data atribut yg memiliki nilai null: ")
print(tipeData_creditProduct)

Jumlah record yang memiliki nilai null: 
ID                      0
Gender                  0
Age                     0
Region_Code             0
Occupation              0
Channel_Code            0
Vintage                 0
Credit_Product         65
Avg_Account_Balance     0
Is_Active               0
Is_Lead                 0
dtype: int64

Tipe data atribut yg memiliki nilai null: 
object


In [256]:
from sklearn.impute import SimpleImputer
SimpleImputer = SimpleImputer(strategy='most_frequent' )
df["Credit_Product"] = SimpleImputer.fit_transform(df[["Credit_Product"]])

print("\nJumlah nilai null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah nilai null setelah menggunakan SimpleImputer: 
ID                     0
Gender                 0
Age                    0
Region_Code            0
Occupation             0
Channel_Code           0
Vintage                0
Credit_Product         0
Avg_Account_Balance    0
Is_Active              0
Is_Lead                0
dtype: int64


- Melakukan <b>Data cleaning</b> pada data dengan <b>nilai duplikat</b>. (Jika tidak ada nilai duplikat pada dataset, maka buatlah menjadi ada)

In [257]:
# menampilkan nilai duplikat dataset
print("Jumlah nilai duplikat pada dataset :", df.duplicated().sum())
df[df.duplicated()]

Jumlah nilai duplikat pada dataset : 0


Empty DataFrame
Columns: [ID, Gender, Age, Region_Code, Occupation, Channel_Code, Vintage, Credit_Product, Avg_Account_Balance, Is_Active, Is_Lead]
Index: []

In [258]:
# membuat nilai duplikat menjadi ada
df = df.append(df.iloc[0:100])
print("Jumlah setelah membuat nilai duplikat     :", df.duplicated().sum())

# melakukan data cleaning dengan nilai duplikat
df.drop_duplicates(inplace=True)
print("Nilai duplikat setelah dilakukan cleaning :", df.duplicated().sum())

Jumlah setelah membuat nilai duplikat     : 100
Nilai duplikat setelah dilakukan cleaning : 0


- <b>Mengganti tipe data</b> salah satu attribute angka

In [259]:
print("Tipe data sebelum diubah :", df.dtypes['Vintage'])
df['Vintage'] = df['Vintage'].astype('float64')
print("Tipe data setelah diubah :", df.dtypes['Vintage'])

Tipe data sebelum diubah : int64
Tipe data setelah diubah : float64


- Melakukan <b>one hot encoding</b> pada dataset yang dimiliki.

In [260]:
from sklearn.preprocessing import OneHotEncoder
print("Sebelum dilakukan Encoding")
df.head()

Sebelum dilakukan Encoding


ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0  NNVBBKZB  Female   73       RG268          Other           X3     43.0   
1  IDD62UNG  Female   30       RG277       Salaried           X1     32.0   
2  HD3DSEMC  Female   56       RG268  Self_Employed           X3     26.0   
3  BF3NC7KV    Male   34       RG270       Salaried           X1     19.0   
4  TEASRWXV  Female   30       RG282       Salaried           X1     33.0   

  Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  
0             No              1045696        No        0  
1             No               581988        No        0  
2             No              1484315       Yes        0  
3             No               470454        No        0  
4             No               886787        No        0

In [261]:
encoder = OneHotEncoder(sparse=False)

In [262]:
print("Melakukan OneHotEncoding pada atribut Credit_Product")
CreditProduct_Encoder = encoder.fit_transform(df[["Credit_Product"]])
credit_product = pd.DataFrame(CreditProduct_Encoder)

df = df.join(credit_product)
df.head()

Melakukan OneHotEncoding pada atribut Credit_Product


ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0  NNVBBKZB  Female   73       RG268          Other           X3     43.0   
1  IDD62UNG  Female   30       RG277       Salaried           X1     32.0   
2  HD3DSEMC  Female   56       RG268  Self_Employed           X3     26.0   
3  BF3NC7KV    Male   34       RG270       Salaried           X1     19.0   
4  TEASRWXV  Female   30       RG282       Salaried           X1     33.0   

  Credit_Product  Avg_Account_Balance Is_Active  Is_Lead    0    1  
0             No              1045696        No        0  1.0  0.0  
1             No               581988        No        0  1.0  0.0  
2             No              1484315       Yes        0  1.0  0.0  
3             No               470454        No        0  1.0  0.0  
4             No               886787        No        0  1.0  0.0

In [263]:
print("Mengubah nama kolom")
df = df.rename(columns={
    0 : 'CreditProduct_No',
    1 : 'CreditProduct_Yes'
})
df.head(10)

Mengubah nama kolom


ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0  NNVBBKZB  Female   73       RG268          Other           X3     43.0   
1  IDD62UNG  Female   30       RG277       Salaried           X1     32.0   
2  HD3DSEMC  Female   56       RG268  Self_Employed           X3     26.0   
3  BF3NC7KV    Male   34       RG270       Salaried           X1     19.0   
4  TEASRWXV  Female   30       RG282       Salaried           X1     33.0   
5  ACUTYTWS    Male   56       RG261  Self_Employed           X1     32.0   
6  ETQCZFEJ    Male   62       RG282          Other           X3     20.0   
7  JJNJUQMQ  Female   48       RG265  Self_Employed           X3     13.0   
8  ZMQFYKCB  Female   40       RG283  Self_Employed           X2     38.0   
9  NVKTFBA2  Female   55       RG268  Self_Employed           X2     49.0   

  Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  CreditProduct_No  \
0             No              1045696        No        0               1.0   
1             No               581988        No        0               1.0   
2             No              1484315       Yes        0               1.0   
3             No               470454        No        0               1.0   
4             No               886787        No        0               1.0   
5             No               544163       Yes        0               1.0   
6             No              1056750       Yes        1               1.0   
7             No               444724       Yes        0               1.0   
8             No              1274284        No        0               1.0   
9            Yes              2014239        No        0               0.0   

   CreditProduct_Yes  
0                0.0  
1                0.0  
2                0.0  
3                0.0  
4                0.0  
5                0.0  
6                0.0  
7                0.0  
8                0.0  
9                1.0

In [264]:
print("Melakukan OneHotEncoding pada atribut Is_Active")
IsActive_Encoder = encoder.fit_transform(df[["Is_Active"]])
is_active = pd.DataFrame(IsActive_Encoder)

df = df.join(is_active)
df.head()

Melakukan OneHotEncoding pada atribut Is_Active


ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0  NNVBBKZB  Female   73       RG268          Other           X3     43.0   
1  IDD62UNG  Female   30       RG277       Salaried           X1     32.0   
2  HD3DSEMC  Female   56       RG268  Self_Employed           X3     26.0   
3  BF3NC7KV    Male   34       RG270       Salaried           X1     19.0   
4  TEASRWXV  Female   30       RG282       Salaried           X1     33.0   

  Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  CreditProduct_No  \
0             No              1045696        No        0               1.0   
1             No               581988        No        0               1.0   
2             No              1484315       Yes        0               1.0   
3             No               470454        No        0               1.0   
4             No               886787        No        0               1.0   

   CreditProduct_Yes    0    1  
0                0.0  1.0  0.0  
1                0.0  1.0  0.0  
2                0.0  0.0  1.0  
3                0.0  1.0  0.0  
4                0.0  1.0  0.0

In [265]:
print("Mengubah nama kolom")
df = df.rename(columns={
    0 : 'IsActive_No',
    1 : 'IsActive_Yes'
})
df.head(10)

Mengubah nama kolom


ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0  NNVBBKZB  Female   73       RG268          Other           X3     43.0   
1  IDD62UNG  Female   30       RG277       Salaried           X1     32.0   
2  HD3DSEMC  Female   56       RG268  Self_Employed           X3     26.0   
3  BF3NC7KV    Male   34       RG270       Salaried           X1     19.0   
4  TEASRWXV  Female   30       RG282       Salaried           X1     33.0   
5  ACUTYTWS    Male   56       RG261  Self_Employed           X1     32.0   
6  ETQCZFEJ    Male   62       RG282          Other           X3     20.0   
7  JJNJUQMQ  Female   48       RG265  Self_Employed           X3     13.0   
8  ZMQFYKCB  Female   40       RG283  Self_Employed           X2     38.0   
9  NVKTFBA2  Female   55       RG268  Self_Employed           X2     49.0   

  Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  CreditProduct_No  \
0             No              1045696        No        0               1.0   
1             No               581988        No        0               1.0   
2             No              1484315       Yes        0               1.0   
3             No               470454        No        0               1.0   
4             No               886787        No        0               1.0   
5             No               544163       Yes        0               1.0   
6             No              1056750       Yes        1               1.0   
7             No               444724       Yes        0               1.0   
8             No              1274284        No        0               1.0   
9            Yes              2014239        No        0               0.0   

   CreditProduct_Yes  IsActive_No  IsActive_Yes  
0                0.0          1.0           0.0  
1                0.0          1.0           0.0  
2                0.0          0.0           1.0  
3                0.0          1.0           0.0  
4                0.0          1.0           0.0  
5                0.0          0.0           1.0  
6                0.0          0.0           1.0  
7                0.0          0.0           1.0  
8                0.0          1.0           0.0  
9                1.0          1.0           0.0