## POSTTEST07
## Rausyanfikr Adi Karmayoga 
## 2009106020

In [ ]:
# Memanggil library tensorflow
import tensorflow as tf

1. Membuat tensor dengan <b>shape(5,5)</b> dengan nilai <b>random</b>

In [ ]:
# Shape = [5, 5]
random_tensor = tf.random.normal([5,5], mean=5, stddev=1.0, seed = 1)
random_tensor.read_value().numpy()

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[4.676135 , 5.991337 , 5.1402426, 6.257397 , 5.099923 ],
       [5.189832 , 4.7128882, 3.2586405, 6.8718753, 2.9895496],
       [3.5326972, 3.727801 , 4.2196264, 5.94073  , 4.9383516],
       [2.9157474, 5.614231 , 3.548908 , 4.113065 , 4.0325913],
       [5.9483185, 4.3025503, 5.5391436, 4.4702992, 2.9894636]],
      dtype=float32)>

2. Membuat tensor dengan <b>shape(5,5)</b> dengan nilai bilangan <b>prima</b> dari sebuah <b>list</b>

In [ ]:
# List bilangan prima
list = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]

# Shape = [5, 5]
prime_tensor = tf.Variable((tf.convert_to_tensor(list, dtype=tf.float32)))
prime_tensor

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

3. <b>Menampilkan dimensi</b> dari kedua variable

In [ ]:
print('Dimensi dari variable random_tensor :', random_tensor.shape)
print('Dimensi dari variable prime_tensor  :', prime_tensor.shape)

Dimensi dari variable random_tensor : (5, 5)
Dimensi dari variable prime_tensor  : (5, 5)


4.  Menampilkan hasil dari perhitungan <b>aritmetika</b> kedua variable tersebut 

In [ ]:
# tf.add() : operator penjumlahan
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 6.676135,  8.991337, 10.140243, 13.257397, 16.099922],
       [18.189833, 21.712889, 22.25864 , 29.871876, 31.98955 ],
       [34.532696, 40.727802, 45.219627, 48.94073 , 51.93835 ],
       [55.91575 , 64.61423 , 64.548904, 71.11307 , 75.03259 ],
       [78.94832 , 83.30255 , 88.53915 , 93.4703  , 99.98946 ]],
      dtype=float32)>

In [ ]:
# tf.subtract() : operator pengurangan
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.676135  ,   2.9913368 ,   0.14024258,  -0.7426028 ,
         -5.900077  ],
       [ -7.810168  , -12.287111  , -15.74136   , -16.128124  ,
        -26.01045   ],
       [-27.467302  , -33.272198  , -36.780373  , -37.05927   ,
        -42.06165   ],
       [-50.08425   , -53.38577   , -57.45109   , -62.886936  ,
        -66.96741   ],
       [-67.05168   , -74.69745   , -77.46085   , -84.5297    ,
        -94.01054   ]], dtype=float32)>

In [ ]:
# tf.multiply() : operator perkalian
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  9.35227 ,  17.97401 ,  25.701214,  43.80178 ,  56.099155],
       [ 67.46782 ,  80.1191  ,  61.91417 , 158.05313 ,  86.69694 ],
       [109.51361 , 137.92863 , 173.00468 , 255.4514  , 232.10252 ],
       [154.5346  , 331.23962 , 216.48338 , 275.57535 , 286.314   ],
       [434.22723 , 339.9015  , 459.7489  , 397.85663 , 289.97797 ]],
      dtype=float32)>

In [ ]:
# tf.divide() : operator pembagian
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[2.3380675 , 1.9971123 , 1.0280485 , 0.89391387, 0.46362936],
       [0.39921787, 0.2772287 , 0.1715074 , 0.2987772 , 0.10308792],
       [0.11395797, 0.10075138, 0.10291772, 0.13815652, 0.10507131],
       [0.0550141 , 0.09515646, 0.05817882, 0.06138903, 0.05679706],
       [0.08148381, 0.05446266, 0.06673667, 0.05022808, 0.03081921]],
      dtype=float32)>

In [ ]:
# tf.pow() : operator perpangkatan
tf.pow(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[2.1866240e+01, 2.1506573e+02, 3.5885422e+03, 3.7562634e+05,
        6.0701572e+07],
       [1.9814957e+09, 2.7917815e+11, 5.5936159e+09, 1.7894978e+19,
        6.2025074e+13],
       [9.8016419e+16, 1.3923583e+21, 4.3274710e+25, 1.8841364e+33,
        3.9660164e+32],
       [4.2829653e+24,           inf, 3.5956646e+33,           inf,
                  inf],
       [          inf,           inf,           inf,           inf,
                  inf]], dtype=float32)>

5. Menampilkan nilai <b>maksimal</b> dan <b>minimal</b> dari variable <b>random_tensor</b>

In [ ]:
# Variable random_tensor
print("Input tensor:\n", random_tensor.numpy())

Input tensor:
 [[4.676135  5.991337  5.1402426 6.257397  5.099923 ]
 [5.189832  4.7128882 3.2586405 6.8718753 2.9895496]
 [3.5326972 3.727801  4.2196264 5.94073   4.9383516]
 [2.9157474 5.614231  3.548908  4.113065  4.0325913]
 [5.9483185 4.3025503 5.5391436 4.4702992 2.9894636]]


In [ ]:
# Nilai maksimal
print('Nilai maksimal berdasarkan kolom :', tf.argmax(random_tensor, axis=0).numpy())
print('Nilai maksimal berdasarkan baris :', tf.argmax(random_tensor, axis=1).numpy())

Nilai maksimal berdasarkan kolom : [4 0 4 1 0]
Nilai maksimal berdasarkan baris : [3 3 3 1 0]


In [ ]:
# Nilai minimal
print('Nilai minimal berdasarkan kolom :', tf.argmin(random_tensor, axis=0).numpy())
print('Nilai minimal berdasarkan baris :', tf.argmin(random_tensor, axis=1).numpy())

Nilai minimal berdasarkan kolom : [3 2 1 3 4]
Nilai minimal berdasarkan baris : [0 4 0 0 4]


6. Menampilkan hasil penggabungan variable random_tensor dengan prime_tensor <b>(concatenation)</b>

In [ ]:
print("Ukuran dari data asli :", random_tensor.shape, prime_tensor.shape)

Ukuran dari data asli : (5, 5) (5, 5)


In [ ]:
concat_tensor_column = tf.concat([random_tensor, prime_tensor], axis=0)
print("Ukuran setelah data digabungkan :", concat_tensor_column.shape)

Ukuran setelah data digabungkan : (10, 5)


7. Menampilkan hasil sorting kedua variable secara <b>descending</b>

In [ ]:
# Descending variable random_tensor
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[6.257397 , 5.991337 , 5.1402426, 5.099923 , 4.676135 ],
       [6.8718753, 5.189832 , 4.7128882, 3.2586405, 2.9895496],
       [5.94073  , 4.9383516, 4.2196264, 3.727801 , 3.5326972],
       [5.614231 , 4.113065 , 4.0325913, 3.548908 , 2.9157474],
       [5.9483185, 5.5391436, 4.4702992, 4.3025503, 2.9894636]],
      dtype=float32)

In [ ]:
# Descending variable prime_tensor
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)